// ---------- language (English / Filipino) ----------
// Phone chrome in the shop's own Tagalog. Filipino terms reuse the desktop
// dictionary (src/renderer/js/i18n.js) so both apps speak alike. English
// values match the long-standing UI text exactly.
const LANG_STRINGS = {
  en: {
    'nav.home': 'Home', 'nav.catalog': 'Catalog', 'nav.sale': 'New Sale',
    'nav.pay': 'Payment', 'nav.clients': 'Clients', 'nav.inventory': 'Inventory',
    'nav.transactions': 'Sales', 'nav.expenses': 'Expenses', 'nav.reports': 'Reports',
    'nav.suppliers': 'Suppliers', 'nav.purchase_orders': 'Purchase Orders',
    'view.catalog.title': 'Catalog', 'view.catalog.sub': 'Browse items & sell quickly',
    'view.clients.title': 'Clients', 'view.clients.sub': 'Balances & payment records',
    'view.sale.title': 'New Sale', 'view.sale.sub': 'Build your cart',
    'view.pay.title': 'Record Payment', 'view.pay.sub': 'Collect from clients',
    'view.inventory.title': 'Inventory', 'view.inventory.sub': 'Stock levels',
    'view.transactions.title': 'Recent Sales', 'view.transactions.sub': 'Invoice history',
    'view.expenses.title': 'Expenses', 'view.expenses.sub': 'Record store expenses',
    'view.suppliers.title': 'Suppliers', 'view.suppliers.sub': 'Vendors & balances',
    'view.purchase-orders.title': 'Purchase Orders', 'view.purchase-orders.sub': 'Stock from suppliers',
    'view.reports.title': 'Reports', 'view.reports.sub': 'Sales, expenses & collections',
    'view.settings.title': 'Settings', 'view.settings.sub': 'Store information',
    'view.stocktake.title': 'Stocktake', 'view.stocktake.sub': 'Count what is really on the shelves',
    'view.audit.title': 'Activity Log', 'view.audit.sub': 'Who did what, newest first',
    'view.help.title': 'Help & Guide', 'view.help.sub': 'How to use this phone',
    'view.debts.title': 'Debts', 'view.debts.sub': 'Who owes, what is overdue',
    'pair.title': 'Connect this phone',
    'pair.instr': 'On the shop computer, open Sidebar → Mobile Access and read the 6-digit code.',
    'pair.name_ph': "Phone name (e.g. Ana's phone)",
    'pair.claim_note': 'QR code accepted — name this phone and tap Connect. Each QR pairs one phone.',
    'pair.code_guide': 'Enter the 6-digit code from the desktop app',
    'pair.connect': 'Connect',
    'pair.foot': 'Already on this shop page ({host})? Just enter the code — no address needed.',
    'pair.session_expired': 'Session expired — enter a fresh code from the desktop app.',
    'pair.disconnected': 'Phone disconnected — pair again with a fresh code from the desktop app.',
    'lock.title': 'Phone locked',
    'lock.sub': "Enter this phone's PIN to open shop data.",
    'lock.unlock': 'Unlock',
    'lock.wrong': 'Wrong PIN',
    'lock.unlocked': 'Unlocked',
    'sale.scan': 'Scan', 'sale.add_items': 'Add Items',
    'sale.search_ph': 'Type to add — name, SKU, or barcode…',
    'sale.no_match': 'No match — try Catalog, Scan, or manual item',
    'sale.empty_a': 'Cart is empty — add items from the Catalog or',
    'sale.empty_manual': 'add a manual item',
    'sale.subtotal': 'Subtotal', 'sale.client': 'Client', 'sale.payment': 'Payment',
    'sale.interest': 'Interest (%/mo)', 'sale.discount': 'Discount (₱)',
    'sale.sc': 'SC/PWD 20% Discount', 'sale.charge': 'Charge to client (credit)',
    'sale.total': 'Total', 'sale.save': 'Save Sale',
    'sale.tender_title': 'Cash tendered', 'sale.tender_exact': 'Exact', 'sale.tender_clear': 'Clear',
    'sale.tender_custom_ph': 'Or type custom amount…',
    'sale.tendered': 'Tendered', 'sale.change': 'Change due', 'sale.dash': '—',
    'sale.retry': '↻ Retry last failed sale',
    'sale.success_title': 'Sale saved', 'sale.print': '🖨️ Print counter receipt',
    'sale.share': '📤 Share receipt', 'sale.new': 'New sale',
    'sale.sending_print': 'Sending to counter printer…',
    'sale.printed_ok': 'Receipt sent to counter printer',
    'sale.failed_keep': 'Sale failed — cart kept, tap Retry',
    'sale.retrying': 'Retrying sale…',
    'home.low_stock': 'Low Stock', 'home.to_restock': 'items to restock',
    'home.all_stocked': 'All stocked up', 'home.view_all': 'View all →',
    'home.left': '{n} left', 'home.out': 'Out of stock',
    'home.recent': 'Recent Sales', 'home.no_sales': 'No sales yet',
    'home.today_sales': "Today's Sales", 'home.profit': 'Profit',
    'home.debts': 'Total Debts', 'home.collected': 'Collected',
    'home.month_sales': 'Month Sales', 'home.expenses': 'Expenses',
    'home.quick': 'Quick Actions', 'home.counter': 'Counter',
    'home.sell': 'Sell',    'home.cashier_sub': 'Cashier phone — sales and payments only',
    'home.stock': 'Stock',
    'alerts.out': 'out of stock', 'alerts.low': 'running low',
    'set.shop_contact': 'Contact', 'set.shop_currency': 'Currency',
    'set.currency_ph': 'Philippine Peso',
    'set.install_title': 'Install app',
    'set.install_hint': 'Tip: use the browser menu → Add to Home Screen for an app icon.',
    'set.install_native': 'Running as the installed Shop Ledger app — nothing else to install.',
    'set.install_btn': 'Install Shop Ledger',
    'set.install_prompt': 'Installs Shop Ledger as a fullscreen app on this phone.',
    'set.pin_title': 'Phone lock',
    'set.pin_desc': "Forgot it? Revoke this phone on the desktop, clear this site's browser data, and pair again.",
    'set.pin_new_ph': 'New PIN (4-8 digits)', 'set.pin_confirm_ph': 'Repeat PIN',
    'set.pin_set': 'Set PIN', 'set.pin_current_ph': 'Current PIN',
    'set.pin_remove': 'Remove PIN', 'set.pin_locknow': 'Lock now',
    'set.pin_disconnect': 'Disconnect', 'set.pin_disconnect_phone': 'Disconnect this phone',
    'set.pin_locked_head': 'This phone{dev} is PIN-locked · auto-locks after 5 idle minutes.',
    'set.pin_lock_this': 'Lock this phone{dev} behind a short PIN.',
    'set.display_title': 'Display',
    'set.display_desc': 'Day mode, larger text, and language.',
    'set.theme_label': 'Theme (day mode for sunlight)',
    'set.text_label': 'Text size',
    'set.day': '☀️ Day', 'set.dark': '🌙 Dark',
    'set.normal': 'Normal', 'set.large': 'Large',
    'set.updates_title': 'App updates',
    'set.checking': 'Checking version…',
    'set.this_app': 'This phone app: ',
    'set.check_updates': 'Check for updates',
    'upd.checking': 'Checking for phone updates…',
    'upd.uptodate': 'This phone app is up to date',
    'upd.unknown': 'Could not check right now — try again later',
    'set.lang_title': 'Language / Wika',
    'set.lang_desc': 'English o Filipino para sa phone na ito.',
    'set.store_note': 'Store details are edited on the desktop app — this page updates on refresh.',
    'set.audit_btn': '📜 Activity log', 'set.help_btn': '❓ Help & guide',
    'set.edit_shop': 'Edit store details',
    'set.shop_name': 'Shop name', 'set.shop_address': 'Address',
    'set.shop_receipt_footer': 'Receipt footer',
    'set.save_shop': 'Save details',
    'set.need_name': 'Enter the shop name',
    'set.save_failed': 'Save failed: {msg}',
    'set.shop_saved': 'Store details saved',
    'common.loading': 'Loading…', 'common.refreshing': '↻ Refreshing…',
    'common.refreshed': 'Refreshed', 'common.close': 'Close',
    'sync.synced_one': '1 change synced',
    'sync.synced_many': '{n} changes synced',
    'sync.pending': '{n} still pending — will retry',
    'sync.none': 'Still no connection — changes stay queued',
    'sync.failed': 'Dropped {n} change(s) the shop rejected',
    'photo.queued': 'Photo queued — will sync when online',
    'scan.point': 'Point at a product barcode…',
    'scan.cancel': 'Cancel',
    'sup.bought': 'Bought {amt}', 'sup.paid': 'Paid {amt}',
    'po.unknown_supplier': 'Unknown supplier',
    'set.default_shop': 'My Sari-Sari Store',
    'set.default_addr': 'Philippines',
    'upd.open_fail': 'Could not open the download',
    'nav.cart_count': '{n} item(s) in cart',
    'diag.title': 'Diagnostics',
    'diag.desc': 'Phone errors queue here and are sent to the shop computer for troubleshooting.',
    'diag.send': 'Send diagnostics',
    'diag.empty': 'No diagnostics queued',
    'diag.empty_short': 'queue empty',
    'diag.sent': 'Diagnostics sent ({n})',
    'diag.failed': 'Send failed: {msg}',
    'diag.pending': '{n} queued',
    'diag.last': 'last sent {at}',
    'bio.title': 'Fingerprint / face unlock',
    'bio.need_pin': 'Set a PIN first — biometrics is a shortcut, not a replacement',
    'bio.unavailable': 'Biometrics not available on this phone',
    'bio.unsupported': 'Biometric unlock needs the installed app on a phone with fingerprint or face set up.',
    'bio.on': 'Biometric unlock on',
    'bio.off': 'Biometric unlock off',
    'bio.on_label': 'On', 'bio.off_label': 'Off',
    'lock.bio_btn': 'Use fingerprint / face',
    'rep.share': 'Share',
    'debts.sms': 'SMS reminders',
    'debts.total': 'Total debts',
    'debts.count': '{n} debtor(s)',
    'debts.overdue': '{n} day(s) overdue',
    'debts.due': 'due {d}',
    'debts.empty': 'No debts — everyone is paid up',
    'debts.sending': 'Sending reminders…',
    'debts.sent': 'Reminders sent to {n}',
    'debts.failed': 'SMS failed: {msg}',
    'sale.each': 'each', 'sale.walkin': 'Walk-in (no client)',
    'sale.zero_cash': '0 (Cash)',
    'sale.queued': 'Sale queued — will sync when online',
    'sale.saved_ok': '✅ Sale saved! {inv}',
    'sale.still_failing': 'Still failing: {msg}',
    'sale.print_failed': 'Print failed: {msg}',
    'sale.no_product': 'No product with barcode {code}',
    'sale.oos_item': '{name} is out of stock',
    'sale.added': 'Added {name}',
    'sale.added_cart': 'Added {name} to cart',
    'sale.need_items': 'Add at least one item',
    'sale.need_client': 'Select a client to charge',
    'sale.fail_generic': 'Sale failed: {msg}',
    'manual.title': 'Add Manual Item', 'manual.name': 'Item name',
    'manual.name_ph': 'e.g. Candies', 'manual.price': 'Price (₱)',
    'manual.qty': 'Qty', 'manual.add': 'Add to Cart',
    'manual.name_req': 'Enter an item name',
    'manual.price_req': 'Enter a valid price',
    'cli.total_clients': 'Total clients', 'cli.total_debts': 'Total debts',
    'cli.search_ph': 'Search clients…', 'cli.pay': 'Payment',
    'cat.search_ph': 'Search items…', 'cat.item': 'item', 'cat.items': 'items',
    'cat.no_match': 'No items match your search', 'cat.empty': 'No items yet',
    'cat.in_stock': '{n} in stock',
    'cat.oos': 'Out of stock',
    'pay.amount': 'Amount', 'pay.method': 'Method', 'pay.full': 'Full',
    'pay.record': 'Record Payment',     'pay.fill': 'Fill in client and amount',
    'pay.edit_title': 'Edit Payment',
    'pay.save_edit': 'Save changes',
    'pay.void': 'Delete',
    'pay.void_confirm': 'Tap again to delete',
    'pay.deleted': 'Payment deleted',
    'pay.updated': 'Payment updated',
    'pay.queued': 'Payment queued — will sync when online',
    'pay.ok': '✅ Payment recorded!', 'pay.failed': 'Error: {msg}',
    'exp.add': 'Add Expense', 'exp.this_month': 'This month',
    'exp.total_recorded': 'Total recorded', 'exp.search_ph': 'Search expenses…',
    'exp.desc': 'Description', 'exp.desc_ph': 'e.g. Electric bill',
    'exp.category': 'Category', 'exp.amount': 'Amount (₱)',
    'exp.date': 'Date', 'exp.payee': 'Payee (optional)',
    'exp.payee_ph': 'Who was paid', 'exp.save': 'Save Expense',
    'exp.need_amount': 'Enter a valid amount',
    'exp.queued': 'Expense queued — will sync when online',
    'exp.ok': '✅ Expense recorded!', 'exp.failed': 'Error: {msg}',
    'exp.pending': 'pending sync',
    'exp.edit_title': 'Edit Expense',
    'exp.delete': 'Delete expense',
    'exp.delete_confirm': 'Tap again to delete',
    'exp.deleted': 'Expense deleted',
    'exp.updated': 'Expense updated',
    'petty.title': 'Petty Cash',
    'petty.add': 'Add funds',
    'petty.take': 'Withdraw',
    'petty.amount_ph': 'Amount',
    'petty.go': 'Confirm',
    'petty.done': 'Petty cash updated',
    'petty.failed': 'Petty cash failed: {msg}',
    'petty.empty': 'No petty cash movements yet',
    'sup.pay': 'Pay', 'sup.pay_title': 'Pay {name}', 'sup.owed': 'Owed {amt}',
    'sup.search_ph': 'Search suppliers…',
    'sup.amount': 'Amount (₱)', 'sup.method': 'Method',
    'sup.record': 'Record payment',
    'sup.recorded': 'Supplier payment recorded',
    'sup.need_amount': 'Enter a valid amount',
    'sup.pay_failed': 'Payment failed: {msg}',
    'sup.add': 'Add Supplier',
    'sup.name': 'Name', 'sup.contact': 'Contact', 'sup.email': 'Email',
    'sup.address': 'Address', 'sup.save': 'Save Supplier',
    'sup.need_name': 'Enter the supplier name',
    'sup.added': 'Supplier added', 'sup.failed': 'Save failed: {msg}',
    'sup.history': 'Recent payments',
    'sup.no_history': 'No payments yet',
    'po.receive': 'Receive stock',
    'po.receive_confirm': 'Tap again to receive',
    'po.received': 'Stock received',
    'po.receive_failed': 'Receive failed: {msg}',
    'po.new': 'New PO', 'po.empty': 'No purchase orders yet',
    'po.sheet': 'New Purchase Order', 'po.supplier': 'Supplier',
    'po.select_supplier': 'Select supplier...', 'po.item': 'Item',
    'po.select_item': 'Select item...', 'po.add_to_po': 'Add to PO',
    'po.no_items': 'No items added', 'po.total': 'Total:',
    'po.create': 'Create PO', 'po.select_item_err': 'Select an item',
    'po.added': 'Added {name} ×{qty}',
    'po.need_supplier': 'Select a supplier',
    'po.queued': 'PO queued — will sync when online',
    'po.created': '✅ PO created! {po}', 'po.failed': 'Error: {msg}',
    'po.owed_suffix': 'owed',
    'cli.add': 'Add Client', 'cli.edit': 'Edit', 'cli.save': 'Save Client',
    'cli.add_title': 'Add Client', 'cli.edit_title': 'Edit Client',
    'cli.name': 'Name', 'cli.phone': 'Phone', 'cli.address': 'Address',
    'cli.due': 'Due date',
    'cli.need_name': 'Enter the client name',
    'cli.added': 'Client added', 'cli.updated': 'Client updated',
    'cli.failed': 'Save failed: {msg}',
    'cli.load_fail': 'Could not load client: {msg}',
    'cli.history_sales': 'Sales', 'cli.history_pay': 'Payments',
    'cli.no_history': 'No records yet',
    'cli.statement': 'Statement',
    'cli.redeem': 'Redeem points',
    'cli.redeem_confirm': 'Tap again to use points',
    'cli.redeemed': 'Redeemed {pts} points ({amt} off)',
    'cli.stmt_title': 'STATEMENT OF ACCOUNT',
    'cli.stmt_pay': 'Payment',
    'cli.stmt_balance': 'BALANCE: {amt}',
    'photo.badtype': 'Photo must be a JPG, PNG, WebP or GIF image',
    'photo.toobig': 'Photo too large even after shrinking — pick a smaller one',
    'photo.saved': 'Product photo saved',
    'photo.failed': 'Photo upload failed: {msg}',
    'photo.take': 'Photo',
    'quick.not_found': 'Item not found',
    'quick.added_cart': 'Added {name} ×{qty} to cart',
    'quick.title': 'Quick Sale', 'quick.subtotal': 'Subtotal',
    'quick.add': 'Add to Cart', 'quick.sell_now': 'Sell Now',
    'txn.total_word': 'total',
    'txn.void': 'Void this sale',
    'txn.void_confirm': 'Tap again to confirm void',
    'txn.voided': 'Sale voided',
    'txn.void_failed': 'Void failed: {msg}',
    'txn.vat_incl': 'Includes {amt} VAT',
    'inv.oos': 'OUT OF STOCK', 'inv.left': '{n} left',
    'inv.low_n': '{n} low stock', 'inv.all_ok': 'All stocked',
    'inv.add': 'Add Item', 'inv.edit': 'Edit Item',
    'inv.count': '{n} items',
    'inv.name': 'Name', 'inv.sku': 'SKU', 'inv.barcode': 'Barcode',
    'inv.category': 'Category', 'inv.sell': 'Sell price (₱)',
    'inv.cost': 'Cost price (₱)', 'inv.stock': 'Stock',
    'inv.min': 'Low-stock alert at', 'inv.unit': 'Unit (pcs, kg…)',
    'inv.expiry': 'Expiry date', 'inv.variants': 'Variants (name + stock, optional)',
    'inv.save': 'Save Item',
    'inv.need_name': 'Enter the item name',
    'inv.added': 'Item added', 'inv.updated': 'Item updated',
    'inv.failed': 'Save failed: {msg}',
    'inv.val_cost': 'Stock value (cost)', 'inv.val_retail': 'Stock value (retail)',
    'inv.val_units': '{n} units',
    'st.start': '📋 Start stocktake — count the shelves',
    'rep.top': 'Top items', 'rep.week': 'Last 7 days',
    'rep.ar_title': 'Debt aging', 'rep.ar_current': 'Current',
    'rep.ar_30': '1–30 days overdue', 'rep.ar_60': '31–60 days overdue',
    'rep.ar_over': 'Over 60 days overdue',
    'rep.sbc': 'Sales by client', 'rep.no_data': 'No data yet',
    'ban.pending': 'pending change(s) — will sync when back online',
    'ban.syncnow': 'Sync now',
    'conn.live': '● Live', 'conn.offline': '⚠ Offline — pulling latest data...',
    'load.connecting': 'Connecting to store…',
    'upd.title': 'Phone app update',
    'upd.body': 'Version {tag} is ready. Download it, then tap the file to install — your pairing and settings stay.',
    'upd.download': 'Download update', 'upd.later': 'Later',
    'txn.print': '🖨️ Print', 'txn.share': '📤 Share',
    'txn.credit': 'Credit', 'txn.paid': 'Paid', 'txn.returned_chip': 'Returned',
    'txn.total': 'Total', 'txn.return': '↩ Return this sale',
    'txn.return_confirm': 'Tap again to confirm return',
    'txn.no_lines': 'No item lines recorded.',
    'txn.returned': 'Sale returned',
    'txn.returned_as': 'Sale returned as {inv}',
    'txn.failed': 'Return failed: {msg}',
    'txn.load_fail': 'Could not load receipt: {msg}',
    'ret.pick_hint': 'Tap lines to return only those items — or return the whole sale below.',
    'ret.selected': 'Return selected ({n})',
    'rep.export': 'Export CSV',
    'share.copied': 'Receipt copied — paste it anywhere',
    'share.unavailable': 'Sharing is not available on this phone',
    'nav.owner_only': 'Owner phones only',
    'upd.downloading': 'Downloading update — tap the file to install',
    'rep.month': 'Month',
    'rep.opening': 'Opening download…',
    'rep.today_profit': "Today's Profit",
    'rep.month_profit': 'Month Profit',
    'rep.load_fail': 'Could not load {m}: {msg}',
    'rep.sold': '{qty} sold',
    'st.search_ph': 'Find an item to count…',
    'st.counted': '{n} counted',
    'st.save': 'Save counted stock',
    'st.note': 'Only items you touch are updated.',
    'st.no_diff': 'No differences to save',
    'st.saved_one': 'Stocktake saved: 1 item updated',
    'st.saved_many': 'Stocktake saved: {n} items updated',
    'st.none': 'Nothing saved',
    'st.more': 'more',
    'aud.search_ph': 'Filter actions…',
    'aud.empty': 'No activity yet',
    'aud.unavailable': 'Activity unavailable',
    'aud.cashier': 'Owner phones only. Cashier phones cannot view the log.',
    'help.s1t': 'Selling at the counter',
    'help.s1b': 'Open <b>New Sale</b>, type to add items (or tap <b>Scan</b> for barcodes), set quantities, enter <b>cash tendered</b> to see change due, then <b>Save Sale</b>. After saving you can print the receipt on the counter printer.',
    'help.s2t': 'Collecting payments',
    'help.s2b': 'Open <b>Payment</b>, pick the client, enter the amount. Balances update on the desktop instantly.',
    'help.s3t': 'Counting stock',
    'help.s3b': 'Open <b>Inventory → Start stocktake</b>, walk the shelves and step each count to what you see. <b>Save counted stock</b> updates only the items you touched.',
    'help.s4t': 'When the internet drops',
    'help.s4b': 'Keep working — sales, payments and expenses <b>queue on this phone</b> and the banner shows the pending count. Tap <b>Sync now</b> when back online. Pull down from the top anytime to refresh.',
    'help.s5t': 'Locking this phone',
    'help.s5b': "Set a PIN in <b>Settings → Phone lock</b>. It auto-locks after 5 idle minutes. Forgot it? Ask the shop to revoke this phone on the desktop, clear this site's browser data, and pair again.",
    'help.s6t': 'Troubleshooting',
    'help.s6b': '<b>Session expired</b> — enter a fresh 6-digit code from Sidebar → Mobile Access on the computer. <b>Camera will not start</b> — barcode scanning needs Chrome/Edge plus an https address (or the Tailscale link). Otherwise use search. <b>Print failed</b> — the thermal printer IP is set on the desktop under Settings; the computer must be on the same network as the printer. <b>Something looks stale</b> — pull down from the top to re-sync with the shop computer.',
    'pin.need4': 'PIN needs at least 4 digits',
    'pin.mismatch': 'PINs do not match',
    'pin.save_fail': 'Could not save PIN on this browser',
    'pin.on': 'Phone lock on', 'pin.off': 'Phone lock off',
    'pin.autolock': 'Locked after 5 minutes idle',
    'pair.connected': 'Phone connected',
    'pair.connected_as': ' as {name}',
    'pair.rejected': 'Pairing rejected',
    'pair.failed': 'Pairing failed',
    'scan.need_browser': 'Barcode scanning needs Chrome or Edge on this phone — use Catalog search instead',
    'scan.need_https': 'Camera needs an https address — use Catalog search, or open the Anywhere (Tailscale) link',
    'scan.blocked': 'Camera blocked — allow camera access or use Catalog search',
    'scan.no_formats': 'Barcode formats unsupported here — use Catalog search',

  },
  fil: {
    'nav.home': 'Bahay', 'nav.catalog': 'Katalogo', 'nav.sale': 'Bagong Benta',
    'nav.pay': 'Bayad', 'nav.clients': 'Mga Kliyente', 'nav.inventory': 'Imbentaryo',
    'nav.transactions': 'Mga Benta', 'nav.expenses': 'Mga Gastos', 'nav.reports': 'Mga Ulat',
    'nav.suppliers': 'Mga Supplier', 'nav.purchase_orders': 'Mga PO',
    'view.catalog.title': 'Katalogo', 'view.catalog.sub': 'Mag-browse at magbenta agad',
    'view.clients.title': 'Mga Kliyente', 'view.clients.sub': 'Mga balanse at rekord ng bayad',
    'view.sale.title': 'Bagong Benta', 'view.sale.sub': 'Buuin ang cart',
    'view.pay.title': 'Mag-record ng Bayad', 'view.pay.sub': 'Mangolekta sa mga kliyente',
    'view.inventory.title': 'Imbentaryo', 'view.inventory.sub': 'Mga antas ng stock',
    'view.transactions.title': 'Mga Huling Benta', 'view.transactions.sub': 'Kasaysayan ng resibo',
    'view.expenses.title': 'Mga Gastos', 'view.expenses.sub': 'I-record ang gastos ng tindahan',
    'view.suppliers.title': 'Mga Supplier', 'view.suppliers.sub': 'Mga vendor at balanse',
    'view.purchase-orders.title': 'Mga PO', 'view.purchase-orders.sub': 'Stock mula sa mga supplier',
    'view.reports.title': 'Mga Ulat', 'view.reports.sub': 'Benta, gastos at koleksyon',
    'view.settings.title': 'Mga Setting', 'view.settings.sub': 'Impormasyon ng tindahan',
    'view.stocktake.title': 'Stocktake', 'view.stocktake.sub': 'Bilangin ang tunay na laman ng shelves',
    'view.audit.title': 'Log ng Aktibidad', 'view.audit.sub': 'Sino ang gumawa, pinakabago muna',
    'view.help.title': 'Tulong at Gabay', 'view.help.sub': 'Paano gamitin ang phone na ito',
    'view.debts.title': 'Mga Utang', 'view.debts.sub': 'Sino ang may utang, ano ang overdue',
    'pair.title': 'Ikonekta ang phone na ito',
    'pair.instr': 'Sa computer ng tindahan, buksan ang Sidebar → Mobile Access at basahin ang 6-digit code.',
    'pair.name_ph': 'Pangalan ng phone (hal. phone ni Ana)',
    'pair.claim_note': 'Tinanggap ang QR — pangalanan ang phone at pindutin ang Ikonekta. Bawat QR ay para sa isang phone.',
    'pair.code_guide': 'Ilagay ang 6-digit code mula sa desktop app',
    'pair.connect': 'Ikonekta',
    'pair.foot': 'Nasa page ka na ng tindahan ({host})? Ilagay lang ang code — hindi na kailangan ng address.',
    'pair.session_expired': 'Nag-expire ang session — humingi ng bagong code mula sa desktop app.',
    'pair.disconnected': 'Nadiskonekta ang phone — mag-pair muli gamit ang bagong code mula sa desktop app.',
    'lock.title': 'Naka-lock ang phone',
    'lock.sub': 'Ilagay ang PIN ng phone para buksan ang data.',
    'lock.unlock': 'I-unlock',
    'lock.wrong': 'Maling PIN',
    'lock.unlocked': 'Na-unlock',
    'sale.scan': 'I-scan', 'sale.add_items': 'Magdagdag',
    'sale.search_ph': 'Mag-type para magdagdag — pangalan, SKU, o barcode…',
    'sale.no_match': 'Walang tugma — subukan ang Catalog, Scan, o manual na item',
    'sale.empty_a': 'Walang laman ang cart — magdagdag mula sa Catalog o',
    'sale.empty_manual': 'magdagdag ng manual na item',
    'sale.subtotal': 'Subtotal', 'sale.client': 'Kliyente', 'sale.payment': 'Bayad',
    'sale.interest': 'Interes (%/buwan)', 'sale.discount': 'Diskwento (₱)',
    'sale.sc': 'Diskwentong SC/PWD 20%', 'sale.charge': 'I-charge sa kliyente (utang)',
    'sale.total': 'Kabuuan', 'sale.save': 'I-save ang Benta',
    'sale.tender_title': 'Iniabot na cash', 'sale.tender_exact': 'Sakto', 'sale.tender_clear': 'Burahin',
    'sale.tender_custom_ph': 'O mag-type ng ibang halaga…',
    'sale.tendered': 'Iniabot', 'sale.change': 'Sukli', 'sale.dash': '—',
    'sale.retry': '↻ Subukang muli ang nabigong benta',
    'sale.success_title': 'Na-save ang benta', 'sale.print': '🖨️ I-print ang resibo',
    'sale.share': '📤 I-share ang resibo', 'sale.new': 'Bagong benta',
    'sale.sending_print': 'Sine-send sa printer…',
    'sale.printed_ok': 'Na-send ang resibo sa printer',
    'sale.failed_keep': 'Nabigo ang benta — buo ang cart, pindutin ang Subukan muli',
    'sale.retrying': 'Sinusubukang muli ang benta…',
    'home.low_stock': 'Mababa ang Stock', 'home.to_restock': 'kailangang i-restock',
    'home.all_stocked': 'Kumpleto ang stock', 'home.view_all': 'Tingnan lahat →',
    'home.left': '{n} ang natira', 'home.out': 'Ubos na',
    'home.recent': 'Mga Huling Benta', 'home.no_sales': 'Wala pang benta',
    'home.today_sales': 'Benta Ngayon', 'home.profit': 'Tubo',
    'home.debts': 'Kabuuang Utang', 'home.collected': 'Nakolekta',
    'home.month_sales': 'Benta ngayong Buwan', 'home.expenses': 'Mga Gastos',
    'home.quick': 'Mabilisang Aksyon', 'home.counter': 'Counter',
    'home.sell': 'Ibenta',
    'home.cashier_sub': 'Cashier phone — benta at bayad lang',
    'home.stock': 'Stock',
    'alerts.out': 'ubos na', 'alerts.low': 'paubos na',
    'set.shop_contact': 'Contact', 'set.shop_currency': 'Currency',
    'set.currency_ph': 'Piso ng Pilipinas',
    'set.install_title': 'I-install ang app',
    'set.install_hint': 'Tip: use the browser menu → Add to Home Screen for an app icon.',
    'set.install_native': 'Tumatakbo bilang installed app — wala nang kailangang i-install.',
    'set.install_btn': 'I-install ang Shop Ledger',
    'set.install_prompt': 'Ini-install ang Shop Ledger bilang fullscreen app sa phone na ito.',
    'set.pin_title': 'Lock ng Phone',
    'set.pin_desc': 'Nakalimutan? I-revoke ang phone na ito sa desktop, burahin ang browser data ng site na ito, at mag-pair muli.',
    'set.pin_new_ph': 'Bagong PIN (4-8 digits)', 'set.pin_confirm_ph': 'Ulitin ang PIN',
    'set.pin_set': 'Mag-set ng PIN', 'set.pin_current_ph': 'Kasalukuyang PIN',
    'set.pin_remove': 'Tanggalin ang PIN', 'set.pin_locknow': 'I-lock ngayon',
    'set.pin_disconnect': 'Idiskonekta', 'set.pin_disconnect_phone': 'Idiskonekta ang phone na ito',
    'set.pin_locked_head': 'Ang phone na ito{dev} ay naka-PIN lock · auto-lock pagkalipas ng 5 minutong idle.',
    'set.pin_lock_this': 'Lagyan ng lock ang phone na ito{dev} ng maikling PIN.',
    'set.display_title': 'Display',
    'set.display_desc': 'Day mode, mas malaking text, at wika.',
    'set.theme_label': 'Tema (day mode para sa sikat ng araw)',
    'set.text_label': 'Laki ng text',
    'set.day': '☀️ Araw', 'set.dark': '🌙 Madilim',
    'set.normal': 'Normal', 'set.large': 'Malaki',
    'set.updates_title': 'Mga update ng app',
    'set.checking': 'Tinitingnan ang bersyon…',
    'set.this_app': 'Ang phone app na ito: ',
    'set.check_updates': 'Tumingin ng mga update',
    'upd.checking': 'Tinitingnan kung may update ang phone…',
    'upd.uptodate': 'Updated ang phone app na ito',
    'upd.unknown': 'Hindi matiningnan ngayon — subukan muli mamaya',
    'set.lang_title': 'Language / Wika',
    'set.lang_desc': 'English o Filipino para sa phone na ito.',
    'set.store_note': 'Ang detalye ng tindahan ay inaayos sa desktop app — nag-a-update ang page na ito sa refresh.',
    'set.audit_btn': '📜 Log ng aktibidad', 'set.help_btn': '❓ Tulong at gabay',
    'set.edit_shop': 'I-edit ang detalye',
    'set.shop_name': 'Pangalan ng tindahan', 'set.shop_address': 'Address',
    'set.shop_receipt_footer': 'Footer ng resibo',
    'set.save_shop': 'I-save ang detalye',
    'set.need_name': 'Ilagay ang pangalan ng tindahan',
    'set.save_failed': 'Nabigo ang pag-save: {msg}',
    'set.shop_saved': 'Na-save ang detalye ng tindahan',
    'common.loading': 'Naglo-load…', 'common.refreshing': '↻ Nire-refresh…',
    'common.refreshed': 'Na-refresh', 'common.close': 'Isara',
    'sync.synced_one': '1 pagbabago na-sync',
    'sync.synced_many': '{n} na pagbabago na-sync',
    'sync.pending': '{n} pa ang pending — susubukan muli',
    'sync.none': 'Wala pa ring connection — mananatiling naka-queue',
    'sync.failed': 'Tinanggal ang {n} pagbabagong tinanggihan',
    'photo.queued': 'Naka-queue ang larawan — isi-sync pag online',
    'scan.point': 'Itutok sa barcode ng produkto…',
    'scan.cancel': 'Kanselahin',
    'sup.bought': 'Binili {amt}', 'sup.paid': 'Binayaran {amt}',
    'po.unknown_supplier': 'Hindi kilalang supplier',
    'set.default_shop': 'My Sari-Sari Store',
    'set.default_addr': 'Philippines',
    'upd.open_fail': 'Hindi mabuksan ang download',
    'nav.cart_count': '{n} item sa cart',
    'diag.title': 'Diagnostics',
    'diag.desc': 'Phone errors queue here and are sent to the shop computer for troubleshooting.',
    'diag.send': 'Send diagnostics',
    'diag.empty': 'No diagnostics queued',
    'diag.empty_short': 'queue empty',
    'diag.sent': 'Diagnostics sent ({n})',
    'diag.failed': 'Send failed: {msg}',
    'diag.pending': '{n} queued',
    'diag.last': 'last sent {at}',
    'bio.title': 'Fingerprint / face unlock',
    'bio.need_pin': 'Set a PIN first — biometrics is a shortcut, not a replacement',
    'bio.unavailable': 'Biometrics not available on this phone',
    'bio.unsupported': 'Biometric unlock needs the installed app on a phone with fingerprint or face set up.',
    'bio.on': 'Biometric unlock on',
    'bio.off': 'Biometric unlock off',
    'bio.on_label': 'On', 'bio.off_label': 'Off',
    'lock.bio_btn': 'Use fingerprint / face',
    'rep.share': 'I-share',
    'debts.sms': 'SMS reminders',
    'debts.total': 'Kabuuang utang',
    'debts.count': '{n} may utang',
    'debts.overdue': '{n} araw nang overdue',
    'debts.due': 'takda sa {d}',
    'debts.empty': 'Walang utang — bayad lahat',
    'debts.sending': 'Nagse-send ng reminders…',
    'debts.sent': 'Na-send ang reminders sa {n}',
    'debts.failed': 'Nabigo ang SMS: {msg}',
    'sale.each': 'bawat isa', 'sale.walkin': 'Walk-in (walang kliyente)',
    'sale.zero_cash': '0 (Cash)',
    'sale.queued': 'Naka-queue ang benta — isi-sync pag online',
    'sale.saved_ok': '✅ Na-save ang benta! {inv}',
    'sale.still_failing': 'Nabigo pa rin: {msg}',
    'sale.print_failed': 'Nabigo ang print: {msg}',
    'sale.no_product': 'Walang produktong may barcode {code}',
    'sale.oos_item': 'Ubos na ang {name}',
    'sale.added': 'Nadagdag ang {name}',
    'sale.added_cart': 'Nadagdag si {name} sa cart',
    'sale.need_items': 'Magdagdag ng kahit isang item',
    'sale.need_client': 'Pumili ng kliyenteng sisingilin',
    'sale.fail_generic': 'Nabigo ang benta: {msg}',
    'manual.title': 'Magdagdag ng Manual na Item', 'manual.name': 'Pangalan ng item',
    'manual.name_ph': 'hal. Candy', 'manual.price': 'Presyo (₱)',
    'manual.qty': 'Dami', 'manual.add': 'Idagdag sa Cart',
    'manual.name_req': 'Maglagay ng pangalan ng item',
    'manual.price_req': 'Maglagay ng wastong presyo',
    'cli.total_clients': 'Kabuuang kliyente', 'cli.total_debts': 'Kabuuang utang',
    'cli.search_ph': 'Maghanap ng kliyente…', 'cli.pay': 'Bayad',
    'cat.search_ph': 'Maghanap ng item…', 'cat.item': 'item', 'cat.items': 'mga item',
    'cat.no_match': 'Walang tumutugmang item', 'cat.empty': 'Wala pang item',
    'cat.in_stock': '{n} ang stock',
    'cat.oos': 'Ubos na',
    'pay.amount': 'Halaga', 'pay.method': 'Paraan', 'pay.full': 'Buo',
    'pay.record': 'I-record ang Bayad',     'pay.fill': 'Punan ang kliyente at halaga',
    'pay.edit_title': 'I-edit ang Bayad',
    'pay.save_edit': 'I-save ang pagbabago',
    'pay.void': 'Tanggalin',
    'pay.void_confirm': 'Pindutin muli para tanggalin',
    'pay.deleted': 'Natanggal ang bayad',
    'pay.updated': 'Na-update ang bayad',
    'pay.queued': 'Naka-queue ang bayad — isi-sync pag online',
    'pay.ok': '✅ Na-record ang bayad!', 'pay.failed': 'Error: {msg}',
    'exp.add': 'Magdagdag ng Gastos', 'exp.this_month': 'Ngayong buwan',
    'exp.total_recorded': 'Kabuuang naitala', 'exp.search_ph': 'Maghanap ng gastos…',
    'exp.desc': 'Paglalarawan', 'exp.desc_ph': 'hal. Electric bill',
    'exp.category': 'Kategorya', 'exp.amount': 'Halaga (₱)',
    'exp.date': 'Petsa', 'exp.payee': 'Binayaran (opsyonal)',
    'exp.payee_ph': 'Sino ang binayaran', 'exp.save': 'I-save ang Gastos',
    'exp.need_amount': 'Maglagay ng wastong halaga',
    'exp.queued': 'Naka-queue ang gastos — isi-sync pag online',
    'exp.ok': '✅ Na-record ang gastos!', 'exp.failed': 'Error: {msg}',
    'exp.pending': 'hinihintay mag-sync',
    'exp.edit_title': 'I-edit ang Gastos',
    'exp.delete': 'Tanggalin ang gastos',
    'exp.delete_confirm': 'Pindutin muli para tanggalin',
    'exp.deleted': 'Natanggal ang gastos',
    'exp.updated': 'Na-update ang gastos',
    'petty.title': 'Petty Cash',
    'petty.add': 'Magdagdag ng pondo',
    'petty.take': 'Mag-withdraw',
    'petty.amount_ph': 'Halaga',
    'petty.go': 'Kumpirmahin',
    'petty.done': 'Na-update ang petty cash',
    'petty.failed': 'Nabigo ang petty cash: {msg}',
    'petty.empty': 'Wala pang galaw sa petty cash',
    'sup.pay': 'Bayaran', 'sup.pay_title': 'Bayaran si {name}', 'sup.owed': 'May utang na {amt}',
    'sup.search_ph': 'Maghanap ng supplier…',
    'sup.amount': 'Halaga (₱)', 'sup.method': 'Paraan',
    'sup.record': 'I-record ang bayad',
    'sup.recorded': 'Na-record ang bayad sa supplier',
    'sup.need_amount': 'Maglagay ng wastong halaga',
    'sup.pay_failed': 'Nabigo ang bayad: {msg}',
    'sup.add': 'Magdagdag ng Supplier',
    'sup.name': 'Pangalan', 'sup.contact': 'Contact', 'sup.email': 'Email',
    'sup.address': 'Address', 'sup.save': 'I-save ang Supplier',
    'sup.need_name': 'Ilagay ang pangalan ng supplier',
    'sup.added': 'Nadagdag ang supplier', 'sup.failed': 'Nabigo ang pag-save: {msg}',
    'sup.history': 'Mga huling bayad',
    'sup.no_history': 'Wala pang bayad',
    'po.receive': 'Tanggapin ang stock',
    'po.receive_confirm': 'Pindutin muli para tanggapin',
    'po.received': 'Natanggap ang stock',
    'po.receive_failed': 'Nabigo ang pagtanggap: {msg}',
    'po.new': 'Bagong PO', 'po.empty': 'Wala pang purchase order',
    'po.sheet': 'Bagong Purchase Order', 'po.supplier': 'Supplier',
    'po.select_supplier': 'Pumili ng supplier...', 'po.item': 'Item',
    'po.select_item': 'Pumili ng item...', 'po.add_to_po': 'Idagdag sa PO',
    'po.no_items': 'Walang item na nadagdag', 'po.total': 'Kabuuan:',
    'po.create': 'Gumawa ng PO', 'po.select_item_err': 'Pumili ng item',
    'po.added': 'Nadagdag si {name} ×{qty}',
    'po.need_supplier': 'Pumili ng supplier',
    'po.queued': 'Naka-queue ang PO — isi-sync pag online',
    'po.created': '✅ Nagawa ang PO! {po}', 'po.failed': 'Error: {msg}',
    'po.owed_suffix': 'utang',
    'cli.add': 'Magdagdag ng Kliyente', 'cli.edit': 'I-edit', 'cli.save': 'I-save ang Kliyente',
    'cli.add_title': 'Magdagdag ng Kliyente', 'cli.edit_title': 'I-edit ang Kliyente',
    'cli.name': 'Pangalan', 'cli.phone': 'Phone', 'cli.address': 'Address',
    'cli.due': 'Takdang petsa',
    'cli.need_name': 'Ilagay ang pangalan ng kliyente',
    'cli.added': 'Nadagdag ang kliyente', 'cli.updated': 'Na-update ang kliyente',
    'cli.failed': 'Nabigo ang pag-save: {msg}',
    'cli.load_fail': 'Hindi ma-load ang kliyente: {msg}',
    'cli.history_sales': 'Mga Benta', 'cli.history_pay': 'Mga Bayad',
    'cli.no_history': 'Wala pang rekord',
    'cli.statement': 'Statement',
    'cli.redeem': 'I-redeem ang points',
    'cli.redeem_confirm': 'Pindutin muli para gamitin ang points',
    'cli.redeemed': 'Na-redeem ang {pts} points ({amt} bawas)',
    'cli.stmt_title': 'STATEMENT OF ACCOUNT',
    'cli.stmt_pay': 'Bayad',
    'cli.stmt_balance': 'BALANSE: {amt}',
    'photo.badtype': 'Kailangang JPG, PNG, WebP o GIF ang larawan',
    'photo.toobig': 'Masyadong malaki ang larawan kahit pinaliit na',
    'photo.saved': 'Na-save ang larawan ng produkto',
    'photo.failed': 'Nabigo ang upload ng larawan: {msg}',
    'photo.take': 'Kuhanan',
    'quick.not_found': 'Hindi mahanap ang item',
    'quick.added_cart': 'Nadagdag si {name} ×{qty} sa cart',
    'quick.title': 'Mabilisang Benta', 'quick.subtotal': 'Subtotal',
    'quick.add': 'Idagdag sa Cart', 'quick.sell_now': 'Ibenta Na',
    'txn.total_word': 'kabuuan',
    'txn.void': 'I-void ang bentang ito',
    'txn.void_confirm': 'Pindutin muli para kumpirmahin',
    'txn.voided': 'Na-void ang benta',
    'txn.void_failed': 'Nabigo ang pag-void: {msg}',
    'txn.vat_incl': 'Kasama ang {amt} VAT',
    'inv.oos': 'UBOS NA', 'inv.left': '{n} ang natira',
    'inv.add': 'Magdagdag ng Item', 'inv.edit': 'I-edit ang Item',
    'inv.count': '{n} na item',
    'inv.name': 'Pangalan', 'inv.sku': 'SKU', 'inv.barcode': 'Barcode',
    'inv.category': 'Kategorya', 'inv.sell': 'Presyong benta (₱)',
    'inv.cost': 'Presyong puhunan (₱)', 'inv.stock': 'Stock',
    'inv.min': 'Alert kapag bumaba sa', 'inv.unit': 'Unit (pcs, kg…)',
    'inv.expiry': 'Petsa ng pag-expire', 'inv.variants': 'Mga variant (pangalan + stock, opsyonal)',
    'inv.save': 'I-save ang Item',
    'inv.need_name': 'Ilagay ang pangalan ng item',
    'inv.added': 'Nadagdag ang item', 'inv.updated': 'Na-update ang item',
    'inv.failed': 'Nabigo ang pag-save: {msg}',
    'inv.val_cost': 'Halaga ng stock (puhunan)', 'inv.val_retail': 'Halaga ng stock (benta)',
    'inv.val_units': '{n} piraso',
    'inv.low_n': '{n} ang mababa', 'inv.all_ok': 'Kumpleto ang stock',
    'st.start': '📋 Simulan ang stocktake — bilangin ang shelves',
    'rep.top': 'Pinakamabenta', 'rep.week': 'Huling 7 araw',
    'rep.ar_title': 'Pagtanda ng utang', 'rep.ar_current': 'Kasalukuyan',
    'rep.ar_30': '1–30 araw overdue', 'rep.ar_60': '31–60 araw overdue',
    'rep.ar_over': 'Higit 60 araw overdue',
    'rep.sbc': 'Benta bawat kliyente', 'rep.no_data': 'Wala pang data',
    'ban.pending': 'pending na pagbabago — isi-sync pagbalik ng online',
    'ban.syncnow': 'I-sync na',
    'conn.live': '● Live', 'conn.offline': '⚠ Offline — kumukuha ng bagong data...',
    'load.connecting': 'Kumokonekta sa tindahan…',
    'upd.title': 'Update ng phone app',
    'upd.body': 'Handa na ang bersyong {tag}. I-download ito, tapos pindutin ang file para i-install — mananatili ang pairing at settings.',
    'upd.download': 'I-download ang update', 'upd.later': 'Mamaya',
    'txn.print': '🖨️ I-print', 'txn.share': '📤 I-share',
    'txn.credit': 'Utang', 'txn.paid': 'Bayad', 'txn.returned_chip': 'Naibalik',
    'txn.total': 'Kabuuan', 'txn.return': '↩ Ibalik ang bentang ito',
    'txn.return_confirm': 'Pindutin muli para kumpirmahin ang pagbalik',
    'txn.no_lines': 'Walang naitalang item.',
    'txn.returned': 'Naibalik ang benta',
    'txn.returned_as': 'Naibalik ang benta bilang {inv}',
    'txn.failed': 'Nabigo ang pagbalik: {msg}',
    'txn.load_fail': 'Hindi ma-load ang resibo: {msg}',
    'ret.pick_hint': 'Pindutin ang mga linyang ibabalik lang — o ibalik ang buong benta sa ibaba.',
    'ret.selected': 'Ibalik ang napili ({n})',
    'rep.export': 'I-export ang CSV',
    'share.copied': 'Na-copy ang resibo — i-paste kahit saan',
    'share.unavailable': 'Hindi available ang sharing sa phone na ito',
    'nav.owner_only': 'Para sa owner lang',
    'upd.downloading': 'Dina-download ang update — pindutin ang file para i-install',
    'rep.month': 'Buwan',
    'rep.opening': 'Binubuksan ang download…',
    'rep.today_profit': 'Tubo Ngayon',
    'rep.month_profit': 'Tubo sa Buwan',
    'rep.load_fail': 'Hindi ma-load ang {m}: {msg}',
    'rep.sold': 'Nabenta {qty}',
    'st.search_ph': 'Humanap ng bibilangin…',
    'st.counted': '{n} ang nabilang',
    'st.save': 'I-save ang nabilang',
    'st.note': 'Ang mga ginalaw mo lang ang maa-update.',
    'st.no_diff': 'Walang pagkakaibang isi-save',
    'st.saved_one': 'Na-save ang stocktake: 1 item na-update',
    'st.saved_many': 'Na-save ang stocktake: {n} na-update',
    'st.none': 'Walang na-save',
    'st.more': 'pa',
    'aud.search_ph': 'I-filter ang mga aksyon…',
    'aud.empty': 'Wala pang aktibidad',
    'aud.unavailable': 'Hindi available ang aktibidad',
    'aud.cashier': 'Para sa owner lang. Hindi makikita ng cashier ang log.',
    'help.s1t': 'Pagbebenta sa counter',
    'help.s1b': 'Buksan ang <b>Bagong Benta</b>, mag-type para magdagdag (o pindutin ang <b>I-scan</b>), itakda ang dami, ilagay ang <b>iniabot na cash</b> para makita ang sukli, tapos <b>I-save ang Benta</b>. Pagkatapos ay puwedeng i-print ang resibo sa counter printer.',
    'help.s2t': 'Pangongolekta ng bayad',
    'help.s2b': 'Buksan ang <b>Bayad</b>, piliin ang kliyente, ilagay ang halaga. Agad na nag-a-update ang balanse sa desktop.',
    'help.s3t': 'Pagbibilang ng stock',
    'help.s3b': 'Buksan ang <b>Imbentaryo → Start stocktake</b>, libutin ang shelves at itakda ang bilang ng bawat item. Ang <b>I-save ang nabilang</b> ay nag-a-update lang ng mga ginalaw mo.',
    'help.s4t': 'Kapag nawala ang internet',
    'help.s4b': 'Tuloy lang — ang benta, bayad at gastos ay <b>naka-queue sa phone na ito</b> at ipinapakita ng banner ang bilang. Pindutin ang <b>Sync now</b> pagbalik ng online. Hilahin pababa mula sa itaas para mag-refresh anumang oras.',
    'help.s5t': 'Pag-lock ng phone na ito',
    'help.s5b': 'Mag-set ng PIN sa <b>Mga Setting → Lock ng Phone</b>. Auto-lock ito pagkalipas ng 5 minutong idle. Nakalimutan? Ipa-revoke ang phone sa desktop, burahin ang browser data ng site, at mag-pair muli.',
    'help.s6t': 'Troubleshooting',
    'help.s6b': '<b>Nag-expire ang session</b> — humingi ng bagong 6-digit code mula sa Sidebar → Mobile Access sa computer. <b>Ayaw gumana ng camera</b> — kailangan ng Chrome/Edge at https address (o Tailscale link) para sa barcode. Kung hindi, gamitin ang search. <b>Nabigo ang print</b> — ang IP ng thermal printer ay nasa desktop Settings; dapat nasa iisang network ang computer at printer. <b>Mukhang luma ang data</b> — hilahin pababa para mag-sync sa shop computer.',
    'pin.need4': 'Kailangan ng hindi bababa sa 4 digits ang PIN',
    'pin.mismatch': 'Hindi magkatugma ang PIN',
    'pin.save_fail': 'Hindi ma-save ang PIN sa browser na ito',
    'pin.on': 'Naka-on ang lock ng phone', 'pin.off': 'Naka-off ang lock ng phone',
    'pin.autolock': 'Naka-lock pagkalipas ng 5 minutong idle',
    'pair.connected': 'Nakakonekta ang phone',
    'pair.connected_as': ' bilang {name}',
    'pair.rejected': 'Tinanggihan ang pagpapares',
    'pair.failed': 'Nabigo ang pagpapares',

    'scan.need_browser': 'Kailangan ng Chrome o Edge sa phone na ito para sa barcode — gamitin na lang ang Catalog search',
    'scan.need_https': 'Kailangan ng https address para sa camera — gamitin ang Catalog search, o buksan ang Anywhere (Tailscale) link',
    'scan.blocked': 'Naka-block ang camera — payagan ang camera o gamitin ang Catalog search',
    'scan.no_formats': 'Hindi suportado ang barcode formats dito — gamitin ang Catalog search',

  }
};
function phoneLang() {
  try { return localStorage.getItem('slpLang') || 'en'; } catch (e) { return 'en'; }
}
// t('sale.total') → 'Total' (or 'Kabuuan'); t('home.left', {n: 3}) fills {n}.
function T(key, vars) {
  const lang = phoneLang();
  let s = (LANG_STRINGS[lang] && LANG_STRINGS[lang][key] != null)
    ? LANG_STRINGS[lang][key]
    : (LANG_STRINGS.en[key] != null ? LANG_STRINGS.en[key] : key);
  if (vars) {
    for (const k of Object.keys(vars)) s = String(s).split('{' + k + '}').join(vars[k]);
  }
  return s;
}
function setPhoneLang(v) {
  try { localStorage.setItem('slpLang', v === 'fil' ? 'fil' : 'en'); } catch (e) {}
  try { document.documentElement.lang = v === 'fil' ? 'fil' : 'en'; } catch (e) {}
  applyStaticLang();
  try { if (typeof refreshAll === 'function') refreshAll(); } catch (e) {}
}
// Static shell labels (bottom nav, tablet nav) carry data-i18n keys.
function applyStaticLang() {
  try {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const k = el.getAttribute('data-i18n');
      if (k) el.textContent = T(k);
    });
  } catch (e) {}
}
